  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lyrics-page
spec:
  template:
    spec:
      containers:
        - name: lyrics-page
          image: image-registry.openshift-image-registry.svc.cluster.local:5000/right-lyrics/lyrics-page:1.3