---
- name: Albums - MariaDB - Secret
  k8s:
    state: present
    definition: "{{ lookup('template', 'albums-service/mariadb-secret.yaml') }}"
    merge_type: merge
- name: Albums - MariaDB - Deployment
  k8s:
    state: present
    definition: "{{ lookup('template', 'albums-service/mariadb-deployment.yaml') }}"
    merge_type: merge
- name: Albums - MariaDB - Service
  k8s:
    state: present
    definition: "{{ lookup('template', 'albums-service/mariadb-service.yaml') }}"
    merge_type: merge
- name: Albums - Deployment
  k8s:
    state: present
    definition: "{{ lookup('template', 'albums-service/albums-deployment.yaml') }}"
    merge_type: merge
- name: Albums - Service
  k8s:
    state: present
    definition: "{{ lookup('template', 'albums-service/albums-service.yaml') }}"
    merge_type: merge
- name: Albums - Route
  k8s:
    state: present
    definition: "{{ lookup('template', 'albums-service/albums-route.yaml') }}"
    merge_type: merge 
- name: Albums - Register Route
  k8s_info:
    api_version: v1
    kind: Route
    name: albums-service
    namespace: "{{ meta.namespace }}"
  register: albums_service_route        
- name: Hits - Redis - Secret
  k8s:
    state: present
    definition: "{{ lookup('template', 'hits-service/redis-secret.yaml') }}"
    merge_type: merge
- name: Hits - Redis - Deployment
  k8s:
    state: present
    definition: "{{ lookup('template', 'hits-service/redis-deployment.yaml') }}"
    merge_type: merge
- name: Hits - Redis - Service
  k8s:
    state: present
    definition: "{{ lookup('template', 'hits-service/redis-service.yaml') }}"
    merge_type: merge
- name: Hits - Deployment
  k8s:
    state: present
    definition: "{{ lookup('template', 'hits-service/hits-deployment.yaml') }}"
    merge_type: merge
- name: Hits - Service
  k8s:
    state: present
    definition: "{{ lookup('template', 'hits-service/hits-service.yaml') }}"
    merge_type: merge
- name: Import - ConfigMap
  k8s:
    state: present
    definition: "{{ lookup('template', 'import-service/import-configmap.yaml') }}"
    merge_type: merge
- name: Import - Deployment
  k8s:
    state: present
    definition: "{{ lookup('template', 'import-service/import-deployment.yaml') }}"
    merge_type: merge
- name: Import - Service
  k8s:
    state: present
    definition: "{{ lookup('template', 'import-service/import-service.yaml') }}"
    merge_type: merge
- name: Lyrics - MongoDB - Secret
  k8s:
    state: present
    definition: "{{ lookup('template', 'lyrics-service/mongo-secret.yaml') }}"
    merge_type: merge
- name: Lyrics - MongoDB - Deployment
  k8s:
    state: present
    definition: "{{ lookup('template', 'lyrics-service/mongo-deployment.yaml') }}"
    merge_type: merge
- name: Lyrics - MongoDB - Service
  k8s:
    state: present
    definition: "{{ lookup('template', 'lyrics-service/mongo-service.yaml') }}"
    merge_type: merge
- name: Lyrics - Deployment
  k8s:
    state: present
    definition: "{{ lookup('template', 'lyrics-service/lyrics-deployment.yaml') }}"
    merge_type: merge
- name: Lyrics - Service
  k8s:
    state: present
    definition: "{{ lookup('template', 'lyrics-service/lyrics-service.yaml') }}"
    merge_type: merge
- name: Lyrics - Route
  k8s:
    state: present
    definition: "{{ lookup('template', 'lyrics-service/lyrics-route.yaml') }}"
    merge_type: merge    
- name: Lyrics - Register Route
  k8s_info:
    api_version: v1
    kind: Route
    name: lyrics-service
    namespace: "{{ meta.namespace }}"
  register: lyrics_service_route      
- name: Songs - PostgreSQL - Secret
  k8s:
    state: present
    definition: "{{ lookup('template', 'songs-service/postgresql-secret.yaml') }}"
    merge_type: merge
- name: Songs - PostgreSQL - Deployment
  k8s:
    state: present
    definition: "{{ lookup('template', 'songs-service/postgresql-deployment.yaml') }}"
    merge_type: merge
- name: Songs - PostgreSQL - Service
  k8s:
    state: present
    definition: "{{ lookup('template', 'songs-service/postgresql-service.yaml') }}"
    merge_type: merge
- name: Songs - Deployment
  k8s:
    state: present
    definition: "{{ lookup('template', 'songs-service/songs-deployment.yaml') }}"
    merge_type: merge
- name: Songs - Service
  k8s:
    state: present
    definition: "{{ lookup('template', 'songs-service/songs-service.yaml') }}"
    merge_type: merge
- name: Songs - Route
  k8s:
    state: present
    definition: "{{ lookup('template', 'songs-service/songs-route.yaml') }}"
    merge_type: merge    
- name: Songs - Register Route
  k8s_info:
    api_version: v1
    kind: Route
    name: songs-service
    namespace: "{{ meta.namespace }}"
  register: songs_service_route   
- name: Keycloak - Service
  k8s:
    state: present
    definition: "{{ lookup('template', 'keycloak/keycloak-service.yaml') }}"
    merge_type: merge    
- name: Keycloak - Route
  k8s:
    state: present
    definition: "{{ lookup('template', 'keycloak/keycloak-route.yaml') }}"
    merge_type: merge    
- name: Keycloak - Register Route
  k8s_info:
    api_version: v1
    kind: Route
    name: keycloak
    namespace: "{{ meta.namespace }}"
  register: keycloak_route           
- name: Lyrics Page - ConfigMap
  k8s:
    state: present
    definition: "{{ lookup('template', 'lyrics-page/page-configmap.yaml') }}"
    merge_type: merge
- name: Lyrics Page - Deployment
  k8s:
    state: present
    definition: "{{ lookup('template', 'lyrics-page/page-deployment.yaml') }}"
    merge_type: merge       
- name: Lyrics Page - Service
  k8s:
    state: present
    definition: "{{ lookup('template', 'lyrics-page/page-service.yaml') }}"
    merge_type: merge
- name: Lyrics Page - Route
  k8s:
    state: present
    definition: "{{ lookup('template', 'lyrics-page/page-route.yaml') }}"
    merge_type: merge
- name: Lyrics Page - Register Route
  k8s_info:
    api_version: v1
    kind: Route
    name: lyrics-page
    namespace: "{{ meta.namespace }}"
  register: lyrics_page_route
- name: Keycloak - ConfigMap
  k8s:
    state: present
    definition: "{{ lookup('template', 'keycloak/keycloak-configmap.yaml') }}"
    merge_type: merge
- name: Keycloak - Deployment
  k8s:
    state: present
    definition: "{{ lookup('template', 'keycloak/keycloak-deployment.yaml') }}"
    merge_type: merge   
- name: Import - Import Data
  k8s:
    state: present
    definition: "{{ lookup('template', 'import-service/import-job.yaml') }}"
    merge_type: merge    