apiVersion: v1
kind: ConfigMap
metadata:
  name: lyrics-ui
  namespace: {{ meta.namespace }}
data:
  config.js: |
    window.SONGS_SERVICE = "http://{{ songs_service_route | json_query('resources[0].spec.host') }}";
    window.LYRICS_SERVICE = "http://{{ lyrics_service_route | json_query('resources[0].spec.host') }}";
    window.ALBUMS_SERVICE = "http://{{ albums_service_route | json_query('resources[0].spec.host') }}";
    window.KEYCLOAK_SERVICE = "http://{{ keycloak_route | json_query('resources[0].spec.host') }}";