apiVersion: v1
kind: ConfigMap
metadata:
  name: lyrics-ui
  namespace: {{ meta.namespace }}
data:
  nginx.conf: |
        # For more information on configuration, see:
        #   * Official English Documentation: http://nginx.org/en/docs/
        #   * Official Russian Documentation: http://nginx.org/ru/docs/

        worker_processes auto;
        error_log /var/log/error.log;
        pid /run/nginx.pid;


        # Load configuration files for the default server block.
        include      /opt/app-root/etc/nginx.default.d/*.conf;

        events {
            worker_connections  1024;
        }

        http {
            log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                            '$status $body_bytes_sent "$http_referer" '
                            '"$http_user_agent" "$http_x_forwarded_for"';

            access_log  /var/log/nginx/access.log  main;

            sendfile        on;
            tcp_nopush      on;
            tcp_nodelay     on;
            keepalive_timeout  65;
            types_hash_max_size 2048;

            include             /etc/nginx/mime.types;
            default_type        application/octet-stream;


            # Load modular configuration files from the /etc/nginx/conf.d directory.
            # See http://nginx.org/en/docs/ngx_core_module.html#include
            # for more information.
            include /opt/app-root/etc/nginx.d/*.conf;

            server {
                listen       8080 default_server;
                listen       [::]:8080 default_server;
                server_name  _;
                root         /opt/app-root/src;

                # Load configuration files for the default server block.
                include      /opt/app-root/etc/nginx.default.d/*.conf;

                location / {
                }

                error_page 404 /404.html;
                location = /40x.html {
                }

                error_page 500 502 503 504  /50x.html;
                location = /50x.html {
                }

                location /auth/ {
                    proxy_pass http://keycloak:8080/auth/;
                    proxy_buffer_size          128k;
                    proxy_buffers              4 256k;
                    proxy_busy_buffers_size    256k;
                    proxy_http_version 1.1;
                }

                location /api/songs {
                    proxy_pass http://songs-service:8080/api/songs;
                    proxy_http_version 1.1;
                }

                location /api/lyrics {
                    proxy_pass http://lyrics-service:8080/api/lyrics;
                    proxy_http_version 1.1;
                }

                location /api/albums {
                    proxy_pass http://albums-service:8080/api/albums;
                    proxy_http_version 1.1;
                }                
            }
        }