bases:
  - ../../base
patchesStrategicMerge:
  - image-patch.yaml
resources:
  - lyrics-ingress.yaml
secretGenerator:
  - name: lyrics-mongodb
    literals:
      - user=right-lyrics
      - password=right-lyrics
      - database=right-lyrics