apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rightlyrics.veicot.io
spec:
  group: veicot.io
  names:
    kind: RightLyrics
    listKind: RightLyricsList
    plural: rightlyrics
    singular: rightlyrics
    shortNames:
    - rl
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
