apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ui-pipeline
spec:
  params:
    - name: GIT_REPOSITORY
      type: string
    - name: GIT_REVISION
      type: string
    - name: IMAGE
      type: string
    - name: OVERLAY
      type: string
  workspaces:
    - name: source
  tasks:
    - name: clone
      taskRef:
        name: git
      workspaces:
        - name: source
          workspace: source
      params:
        - name: REPOSITORY
          value: $(params.GIT_REPOSITORY)
        - name: REVISION
          value: $(params.GIT_REVISION)    
    - name: build
      taskRef:
        name: s2i
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: source
      params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: BASE_IMAGE
          value: registry.access.redhat.com/rhscl/nodejs-10-rhel7
        - name: CONTEXT_PATH
          value: lyrics-ui/build
        - name: TLS_VERIFY
          value: "false"
    - name: deploy
      taskRef:
        name: kubectl
      runAfter:
        - build
      workspaces:
        - name: source
          workspace: source
      params:
        - name: COMMAND
          value: apply -k $(workspaces.source.path)/lyrics-ui/k8s/overlays/$(params.OVERLAY)