
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: keycloak
spec:
  rules:
    - host: keycloak.right.lyrics
      http:
        paths:
          - path: /
            backend:
              serviceName: keycloak
              servicePort: 8080
