---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lyrics-operator
  labels:
    app.openshift.io/runtime: ansible 
    app.kubernetes.io/part-of: right-lyrics
spec:
  replicas: 1
  selector:
    matchLabels:
      name: lyrics-operator
  template:
    metadata:
      labels:
        name: lyrics-operator
    spec:
      serviceAccountName: lyrics-operator
      containers:
        - name: lyrics-operator          
          image: quay.io/right-lyrics/operator:1.3
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: lyrics-operator
            - name: ANSIBLE_GATHERING
              value: explicit
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 5
            periodSeconds: 3
      volumes:
        - name: runner
          emptyDir: {}
