
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: albums
spec:
  rules:
    - host: right.lyrics
      http:
        paths:
          - path: /api/albums
            pathType: Prefix
            backend:
              service:
                name: albums-service
                port: 8080
