bases:
  - ../../base
patchesStrategicMerge:
  - image-patch.yaml
resources:
  - albums-ingress.yaml
secretGenerator:
  - name: albums-mariadb
    literals:
      - user=rl
      - password=rl
      - database=rl
