apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: songs-postgresql,hits-service
  labels:
    app: songs-service
    version: "1.3"
    app.openshift.io/runtime: spring
    app.kubernetes.io/part-of: right-lyrics
  name: songs-service-v-1-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: songs-service
      version: "1.3"
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: songs-service
        version: "1.3"
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc.cluster.local:5000/right-lyrics/songs-service:1.3
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: songs-postgresql
                  key: password
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: songs-postgresql
                  key: user
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://songs-postgresql:5432/right-lyrics
            - name: HITS_SERVICE_URL
              value: http://hits-service:8080
          imagePullPolicy: Always
          name: songs-service
          ports:
            - containerPort: 8080