apiVersion: v1
kind: Service
metadata:
  labels:
    app: import-service
  name: import-service
  namespace: {{ meta.namespace }}
spec:
  ports:
    - name: tcp-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: import-service