apiVersion: v1
kind: Route
metadata:
  labels:
    app: albums-service
  name: albums-service
  namespace: {{ meta.namespace }}
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: albums-service