apiVersion: v1
kind: Route
metadata:
  labels:
    app: lyrics-service
  name: lyrics-service
  namespace: {{ meta.namespace }}
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: lyrics-service