bases:
  - ../../base
patchesStrategicMerge:
  - resources-patch.yaml
resources:
  - albums-route.yaml  
secretGenerator:
  - name: albums-mariadb
    literals:
      - user=rl
      - password=rl
      - database=rl
